// <auto-generated />
using KormoranAdminSystemRevamped.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KormoranAdminSystemRevamped.Migrations
{
    [DbContext(typeof(KormoranContext))]
    [Migration("20211127190527_AddedNewEnumTables")]
    partial class AddedNewEnumTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("KormoranAdminSystemRevamped.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("discipline");
                });

            modelBuilder.Entity("KormoranAdminSystemRevamped.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("KormoranAdminSystemRevamped.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("StateId")
                        .HasColumnType("int(11)")
                        .HasColumnName("state");

                    b.Property<string>("TournamentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_type");

                    b.Property<string>("TournamentTypeShort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_type_short");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StateId");

                    b.ToTable("tournaments");
                });

            modelBuilder.Entity("KormoranAdminSystemRevamped.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pass");

                    b.Property<string>("Permissions")
                        .HasColumnType("json")
                        .HasColumnName("permissions");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("KormoranAdminSystemRevamped.Models.Tournament", b =>
                {
                    b.HasOne("KormoranAdminSystemRevamped.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KormoranAdminSystemRevamped.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
